package com.foodscanner.service



val allergenTranslations = mapOf(

    "de" to mapOf(
        "milk" to "Milch",
        "kiwi" to "Kiwi",
        "chicken" to "Hähnchen",
        "red-caviar" to "Roter Kaviar",
        "orange" to "Orange",
        "peanuts" to "Erdnüsse",
        "eggs" to "Eier",
        "matsutake" to "Matsutake",
        "gluten" to "Gluten",
        "lupin" to "Lupine",
        "yamaimo" to "Yamaimo",
        "apple" to "Apfel",
        "sulphur-dioxide-and-sulphites" to "Schwefeldioxid und Sulfite",
        "fish" to "Fisch",
        "none" to "Keine",
        "molluscs" to "Weichtiere",
        "nuts" to "Schalenfrüchte",
        "pork" to "Schweinefleisch",
        "crustaceans" to "Krebstiere",
        "mustard" to "Senf",
        "celery" to "Sellerie",
        "banana" to "Banane",
        "soybeans" to "Soja",
        "sesame-seeds" to "Sesam",
        "gelatin" to "Gelatine",
        "peach" to "Pfirsich",
        "beef" to "Rindfleisch"
    ),
    "en" to mapOf(
        "milk" to "Milk",
        "kiwi" to "Kiwi",
        "chicken" to "Chicken",
        "red-caviar" to "Red-Caviar",
        "orange" to "Orange",
        "peanuts" to "Peanuts",
        "eggs" to "Eggs",
        "matsutake" to "Matsutake",
        "gluten" to "Gluten",
        "lupin" to "Lupin",
        "yamaimo" to "Yamaimo",
        "apple" to "Apple",
        "sulphur-dioxide-and-sulphites" to "Sulphur-Dioxide-and-Sulphites",
        "fish" to "Fish",
        "none" to "None",
        "molluscs" to "Molluscs",
        "nuts" to "Nuts",
        "pork" to "Pork",
        "crustaceans" to "Crustaceans",
        "mustard" to "Mustard",
        "celery" to "Celery",
        "banana" to "Banana",
        "soybeans" to "Soybeans",
        "sesame-seeds" to "Sesame-Seeds",
        "gelatin" to "Gelatin",
        "peach" to "Peach",
        "beef" to "Beef"
    )

)



val labelTranslations = mapOf(
    "de" to mapOf(
        "en:vegan" to "Vegan",
        "en:vegetarian" to "Vegetarisch",
        "en:organic" to "Bio",
        "en:fair-trade" to "Fair Trade",
        "en:halal" to "Halal",
        "en:kosher" to "Koscher",
        "en:gluten-free" to "Glutenfrei",
        "en:lactose-free" to "Laktosefrei",
        "en:no-added-sugar" to "Ohne Zuckerzusatz",
        "en:no-added-salt" to "Ohne Salzzusatz",
        "en:no-palm-oil" to "Ohne Palmöl",
        "en:palm-oil-free" to "Palmölfrei",
        "en:low-fat" to "Fettarm",
        "en:low-sugar" to "Zuckerarm",
        "en:high-protein" to "Proteinreich",
        "en:source-of-fiber" to "Ballaststoffquelle",
        "en:high-fiber" to "Ballaststoffreich",
        "en:non-gmo" to "Ohne Gentechnik",
        "en:gmo-free" to "Gentechnikfrei",
        "en:free-range" to "Freilandhaltung",
        "en:sustainably-sourced" to "Nachhaltige Herkunft",
        "en:rainforest-alliance" to "Rainforest Alliance",
        "en:made-in-eu" to "Hergestellt in der EU",
        "en:local" to "Regional",
        "en:made-in-germany" to "Hergestellt in Deutschland",
        "en:nutriscore" to "Nutri-Score",
        "en:ecoscore" to "Eco-Score"
    ),
    "en" to mapOf(
        "en:vegan" to "Vegan",
        "en:vegetarian" to "Vegetarian",
        "en:organic" to "Organic",
        "en:fair-trade" to "Fair Trade",
        "en:halal" to "Halal",
        "en:kosher" to "Kosher",
        "en:gluten-free" to "Gluten-Free",
        "en:lactose-free" to "Lactose-Free",
        "en:no-added-sugar" to "No Added Sugar",
        "en:no-added-salt" to "No Added Salt",
        "en:no-palm-oil" to "No Palm Oil",
        "en:palm-oil-free" to "Palm Oil Free",
        "en:low-fat" to "Low Fat",
        "en:low-sugar" to "Low Sugar",
        "en:high-protein" to "High Protein",
        "en:source-of-fiber" to "Source of Fiber",
        "en:high-fiber" to "High Fiber",
        "en:non-gmo" to "Non-GMO",
        "en:gmo-free" to "GMO-Free",
        "en:free-range" to "Free Range",
        "en:sustainably-sourced" to "Sustainably Sourced",
        "en:rainforest-alliance" to "Rainforest Alliance",
        "en:made-in-eu" to "Made in the EU",
        "en:local" to "Local / Regional",
        "en:made-in-germany" to "Made in Germany",
        "en:nutriscore" to "Nutri-Score",
        "en:ecoscore" to "Eco-Score"
    )
)